// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXhjzaRmTD6D3wPWpf6iTKRbm1YSU8nI',
    appId: '1:708188376121:web:a7655d2a0cb7d7cca4d1e8',
    messagingSenderId: '708188376121',
    projectId: 'blaberfy-14b59',
    authDomain: 'blaberfy-14b59.firebaseapp.com',
    storageBucket: 'blaberfy-14b59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5ttExEHfaBrp_wQVtk8k1wtpwFhA7kk',
    appId: '1:708188376121:android:ead1da89bc83e06ba4d1e8',
    messagingSenderId: '708188376121',
    projectId: 'blaberfy-14b59',
    storageBucket: 'blaberfy-14b59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbym2kit7erAnBgi5k5McjkFO2P1N2y5U',
    appId: '1:708188376121:ios:ef53809da54ec0a8a4d1e8',
    messagingSenderId: '708188376121',
    projectId: 'blaberfy-14b59',
    storageBucket: 'blaberfy-14b59.appspot.com',
    iosBundleId: 'com.example.blabberfy',
  );
}
